### PR TITLE
Operation Resubmission

### PR DESCRIPTION
**Pull request by awrichar**
See https://github.com/hyperledger/firefly/issues/400

### CODE REVIEW

**Comment by awrichar** [comment]
Thanks for the comments - very helpful.

> the operation manager knows to update an existing one, rather than generating a lot of new ones.

This feels right on some levels, although we said previously that for user-initiated retries, a new operation ID should be generated every time in order to properly correlate backend responses. We _could_ decide specifically that machine-initiated retries are different, and can be sent over and over with the same ID (and the status/outputs will get replaced every time there is a response). Need to mentally work this out further.

Other options are to do a delete+replace of the operation (which bears some risk of getting a late, uncorrelated response), or to insert the operation only after the operation succeeds (which is what we originally did in some cases, but doesn't even solve the problem if there are multiple ops and it's a later one that fails).

In all cases we may have the ability to detect and put some "special" status on operations that end up in this looping state. Perhaps this is the "blocked" state that we suspected was going to work its way in at some point.

**Comment by awrichar** [comment]
> move the code that does the IPFS upload, to the batch processor

I'm going to work this out and can put up a separate PR (probably after #517 closes). I've been feeling like this is the way to go, so we can discuss more once we see what it looks like.

**Comment by peterbroadhurst** [comment]
>  a new operation ID should be generated every time in order to properly correlate backend responses

100% agree with this, and your other commentary. Think we're aligned on the considerations around the automated-retry architecture.

**Comment by awrichar** [comment]
Another small item, but I believe the route `/namespaces/{ns}/messages/{msgid}/operations` should be removed as part of this change. Operations are closely tied to Transactions and Batches, but they're really a step removed from Messages. Will add this into the text of the FIR as well.

**Pull request merged**
